"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authError = exports.missingFields = exports.emailExist = exports.onDelete = exports.onUpdate = exports.onCreate = exports.resend = exports.passwordUpdated = exports.passwordMatch = exports.passwordReset = exports.noEmailAssociate = exports.thisAccountVerified = exports.emailAssociate = exports.userVerification = exports.accountVerified = exports.emailConfirmation = exports.duplicateUsername = exports.login = exports.loged = exports.logout = exports.duplicateEmail = exports.signedup = void 0;
exports.signedup = "You signed up successfully";
exports.duplicateEmail = "This account with this email already exist";
exports.logout = "You loged out successfully";
exports.loged = "You aleady Logged Out";
exports.login = "Please Login";
exports.duplicateUsername = "This Username is in use";
exports.emailConfirmation = "A verification email has been sent to ";
exports.accountVerified = "The account has been verified. Please log in.";
exports.userVerification = "This user has already been verified.";
exports.emailAssociate = "we are unable to find a user with that email!";
exports.thisAccountVerified = "This account has  already been verified.Please log In";
exports.noEmailAssociate = "no account associated to this email";
exports.passwordReset = "The link to reset password sent succesfully to your email!";
exports.passwordMatch = "password don't match";
exports.passwordUpdated = "password updated succesfully!";
exports.resend = "confirmation email resend succesfully!";
exports.onCreate = "Request submitted";
exports.onUpdate = "Request updated!";
exports.onDelete = "Request deleted";
exports.emailExist = "User already exists with that email";
exports.missingFields = "Please Fill on all the fields";
exports.authError = "Invalid Email or password";
