"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.serverError = exports.unprocessableEntity = exports.conflict = exports.notFound = exports.forbidden = exports.unAuthorized = exports.badRequest = exports.created = exports.ok = void 0;
exports.ok = 200;
exports.created = 201;
exports.badRequest = 400;
exports.unAuthorized = 401;
exports.forbidden = 403;
exports.notFound = 404;
exports.conflict = 409;
exports.unprocessableEntity = 422;
exports.serverError = 500;
